#!/usr/bin/env bash
set -e

pip install -e .

jupyter serverextension enable --py idom_jupyter
jupyter nbextension install --py --symlink --sys-prefix idom_jupyter
jupyter nbextension enable --py --sys-prefix idom_jupyter
# jupyter labextension install js
